import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import AuthContext from "./context/AuthContext";
import { AuthProvider } from "./Providers";

const roboto = Roboto({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Church membership",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <AuthContext>
          <AuthProvider>{children}</AuthProvider>
        </AuthContext>
      </body>
    </html>
  );
}
